# Generated by Django 4.2 on 2023-05-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0002_alter_buser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buser',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='BlogApp.buser'),
        ),
        migrations.AlterField(
            model_name='buser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
