# Generated by Django 4.2 on 2023-05-15 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
                ('flies_europe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Baloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('manufacturer', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('total_hours', models.IntegerField()),
                ('rank', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flght',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name_airport_departure', models.TextField()),
                ('name_airport_arrival', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalloonApp.airline')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalloonApp.pilot')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='cooperation_pilots',
            field=models.ManyToManyField(to='BalloonApp.pilot'),
        ),
    ]
