# Generated by Django 4.2 on 2023-05-15 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BalloonApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flght',
            new_name='Flight',
        ),
    ]
